
#APP SECRETS

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-secrets
  namespace: app
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjpTUGlUbUl6U2IwWGJWU082c3pDYXMxMkB0YXNrLW1hbmFnZXIuY2NpOXEubW9uZ29kYi5uZXQvdGFzay1tYW5hZ2VyP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==

